<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TABLETS</name>
   <tag></tag>
   <elementGuidId>dc171f9c-0e14-4e4d-92b6-39a546211143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='tabletsTxt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tabletsTxt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>089ac6b5-4fbf-4ca1-a096-c601b99c554e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabletsTxt</value>
      <webElementGuid>fe96c19e-bbc1-419e-8fae-8c56571315d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>TabletsCategoryTxt</value>
      <webElementGuid>df12d744-0925-41a9-a843-7cd524b18bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_now roboto-bold ng-binding</value>
      <webElementGuid>e702b193-bb56-48f5-b990-1c52b7849926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>058dfdc6-36bb-4835-9bb0-28bbfbefc6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>66a38e13-3884-4255-8858-ec97361547d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TABLETS</value>
      <webElementGuid>d9a9d55e-d614-4a0b-b120-cf36376435d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabletsTxt&quot;)</value>
      <webElementGuid>3d57c843-7f5c-4285-9cc8-6fbf7435b1bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='tabletsTxt']</value>
      <webElementGuid>2b47b12e-acde-4398-8306-17b0613e494d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabletsImg']/div/span</value>
      <webElementGuid>b7a3b217-aa52-4a30-add2-fdcbe46d7f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[1]/following::span[1]</value>
      <webElementGuid>ac5577c0-7cc5-4893-b2cc-d7aa36b19f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPEAKERS'])[1]/following::span[1]</value>
      <webElementGuid>a9602c2b-101d-437c-903a-c5cb7b0a8a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[2]/preceding::span[1]</value>
      <webElementGuid>b8b0659f-9a22-4b6d-bbf3-fda8b6caaf49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LAPTOPS'])[1]/preceding::span[1]</value>
      <webElementGuid>7eedd059-60a2-4ca8-b421-a6338e0a07a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TABLETS']/parent::*</value>
      <webElementGuid>2c5774f0-0dc4-4b88-84c6-0cae229b6620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>92f9da8d-96b5-4283-b708-d4e148d5e3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'tabletsTxt' and @href = 'javascript:void(0)' and (text() = 'TABLETS' or . = 'TABLETS')]</value>
      <webElementGuid>bb3ef720-8355-4d87-8454-abe754f22759</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
